// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: keeper.proto

package keeperservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Register_FullMethodName = "/api.AuthService/Register"
	AuthService_Login_FullMethodName    = "/api.AuthService/Login"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AuthService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keeper.proto",
}

const (
	StorageService_CreateAuthInfo_FullMethodName     = "/api.StorageService/CreateAuthInfo"
	StorageService_GetAuthInfo_FullMethodName        = "/api.StorageService/GetAuthInfo"
	StorageService_UpdateAuthInfo_FullMethodName     = "/api.StorageService/UpdateAuthInfo"
	StorageService_DeleteAuthInfo_FullMethodName     = "/api.StorageService/DeleteAuthInfo"
	StorageService_SetTextInfo_FullMethodName        = "/api.StorageService/SetTextInfo"
	StorageService_SetFileChunkInfo_FullMethodName   = "/api.StorageService/SetFileChunkInfo"
	StorageService_SetBankCardDetails_FullMethodName = "/api.StorageService/SetBankCardDetails"
	StorageService_GetTextInfo_FullMethodName        = "/api.StorageService/GetTextInfo"
	StorageService_GetFileChunkInfo_FullMethodName   = "/api.StorageService/GetFileChunkInfo"
	StorageService_GetBankCardDetails_FullMethodName = "/api.StorageService/GetBankCardDetails"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServiceClient interface {
	CreateAuthInfo(ctx context.Context, in *CreateAuthInfoRequest, opts ...grpc.CallOption) (*CreateAuthInfoResponse, error)
	GetAuthInfo(ctx context.Context, in *GetAuthInfoRequest, opts ...grpc.CallOption) (*GetAuthInfoResponse, error)
	UpdateAuthInfo(ctx context.Context, in *UpdateAuthInfoRequest, opts ...grpc.CallOption) (*UpdateAuthInfoResponse, error)
	DeleteAuthInfo(ctx context.Context, in *DeleteAuthInfoRequest, opts ...grpc.CallOption) (*DeleteAuthInfoResponse, error)
	SetTextInfo(ctx context.Context, in *TextInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetFileChunkInfo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunkInfo, emptypb.Empty], error)
	SetBankCardDetails(ctx context.Context, in *BankCardDetails, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetTextInfo(ctx context.Context, in *RequestTitle, opts ...grpc.CallOption) (*TextInfoList, error)
	GetFileChunkInfo(ctx context.Context, in *RequestFileName, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunkInfo], error)
	GetBankCardDetails(ctx context.Context, in *RequestCardNumber, opts ...grpc.CallOption) (*BankCardDetailsList, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) CreateAuthInfo(ctx context.Context, in *CreateAuthInfoRequest, opts ...grpc.CallOption) (*CreateAuthInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAuthInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_CreateAuthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetAuthInfo(ctx context.Context, in *GetAuthInfoRequest, opts ...grpc.CallOption) (*GetAuthInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_GetAuthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UpdateAuthInfo(ctx context.Context, in *UpdateAuthInfoRequest, opts ...grpc.CallOption) (*UpdateAuthInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAuthInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_UpdateAuthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteAuthInfo(ctx context.Context, in *DeleteAuthInfoRequest, opts ...grpc.CallOption) (*DeleteAuthInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAuthInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteAuthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SetTextInfo(ctx context.Context, in *TextInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorageService_SetTextInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SetFileChunkInfo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunkInfo, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_SetFileChunkInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunkInfo, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_SetFileChunkInfoClient = grpc.ClientStreamingClient[FileChunkInfo, emptypb.Empty]

func (c *storageServiceClient) SetBankCardDetails(ctx context.Context, in *BankCardDetails, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorageService_SetBankCardDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetTextInfo(ctx context.Context, in *RequestTitle, opts ...grpc.CallOption) (*TextInfoList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextInfoList)
	err := c.cc.Invoke(ctx, StorageService_GetTextInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetFileChunkInfo(ctx context.Context, in *RequestFileName, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunkInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[1], StorageService_GetFileChunkInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestFileName, FileChunkInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_GetFileChunkInfoClient = grpc.ServerStreamingClient[FileChunkInfo]

func (c *storageServiceClient) GetBankCardDetails(ctx context.Context, in *RequestCardNumber, opts ...grpc.CallOption) (*BankCardDetailsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankCardDetailsList)
	err := c.cc.Invoke(ctx, StorageService_GetBankCardDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
type StorageServiceServer interface {
	CreateAuthInfo(context.Context, *CreateAuthInfoRequest) (*CreateAuthInfoResponse, error)
	GetAuthInfo(context.Context, *GetAuthInfoRequest) (*GetAuthInfoResponse, error)
	UpdateAuthInfo(context.Context, *UpdateAuthInfoRequest) (*UpdateAuthInfoResponse, error)
	DeleteAuthInfo(context.Context, *DeleteAuthInfoRequest) (*DeleteAuthInfoResponse, error)
	SetTextInfo(context.Context, *TextInfo) (*emptypb.Empty, error)
	SetFileChunkInfo(grpc.ClientStreamingServer[FileChunkInfo, emptypb.Empty]) error
	SetBankCardDetails(context.Context, *BankCardDetails) (*emptypb.Empty, error)
	GetTextInfo(context.Context, *RequestTitle) (*TextInfoList, error)
	GetFileChunkInfo(*RequestFileName, grpc.ServerStreamingServer[FileChunkInfo]) error
	GetBankCardDetails(context.Context, *RequestCardNumber) (*BankCardDetailsList, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) CreateAuthInfo(context.Context, *CreateAuthInfoRequest) (*CreateAuthInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuthInfo not implemented")
}
func (UnimplementedStorageServiceServer) GetAuthInfo(context.Context, *GetAuthInfoRequest) (*GetAuthInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthInfo not implemented")
}
func (UnimplementedStorageServiceServer) UpdateAuthInfo(context.Context, *UpdateAuthInfoRequest) (*UpdateAuthInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAuthInfo not implemented")
}
func (UnimplementedStorageServiceServer) DeleteAuthInfo(context.Context, *DeleteAuthInfoRequest) (*DeleteAuthInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAuthInfo not implemented")
}
func (UnimplementedStorageServiceServer) SetTextInfo(context.Context, *TextInfo) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTextInfo not implemented")
}
func (UnimplementedStorageServiceServer) SetFileChunkInfo(grpc.ClientStreamingServer[FileChunkInfo, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method SetFileChunkInfo not implemented")
}
func (UnimplementedStorageServiceServer) SetBankCardDetails(context.Context, *BankCardDetails) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBankCardDetails not implemented")
}
func (UnimplementedStorageServiceServer) GetTextInfo(context.Context, *RequestTitle) (*TextInfoList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTextInfo not implemented")
}
func (UnimplementedStorageServiceServer) GetFileChunkInfo(*RequestFileName, grpc.ServerStreamingServer[FileChunkInfo]) error {
	return status.Error(codes.Unimplemented, "method GetFileChunkInfo not implemented")
}
func (UnimplementedStorageServiceServer) GetBankCardDetails(context.Context, *RequestCardNumber) (*BankCardDetailsList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBankCardDetails not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_CreateAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreateAuthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateAuthInfo(ctx, req.(*CreateAuthInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetAuthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetAuthInfo(ctx, req.(*GetAuthInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UpdateAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAuthInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).UpdateAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_UpdateAuthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).UpdateAuthInfo(ctx, req.(*UpdateAuthInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAuthInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteAuthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteAuthInfo(ctx, req.(*DeleteAuthInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SetTextInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SetTextInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_SetTextInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SetTextInfo(ctx, req.(*TextInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SetFileChunkInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).SetFileChunkInfo(&grpc.GenericServerStream[FileChunkInfo, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_SetFileChunkInfoServer = grpc.ClientStreamingServer[FileChunkInfo, emptypb.Empty]

func _StorageService_SetBankCardDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankCardDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SetBankCardDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_SetBankCardDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SetBankCardDetails(ctx, req.(*BankCardDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetTextInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTitle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetTextInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetTextInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetTextInfo(ctx, req.(*RequestTitle))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetFileChunkInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestFileName)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).GetFileChunkInfo(m, &grpc.GenericServerStream[RequestFileName, FileChunkInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_GetFileChunkInfoServer = grpc.ServerStreamingServer[FileChunkInfo]

func _StorageService_GetBankCardDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCardNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetBankCardDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetBankCardDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetBankCardDetails(ctx, req.(*RequestCardNumber))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuthInfo",
			Handler:    _StorageService_CreateAuthInfo_Handler,
		},
		{
			MethodName: "GetAuthInfo",
			Handler:    _StorageService_GetAuthInfo_Handler,
		},
		{
			MethodName: "UpdateAuthInfo",
			Handler:    _StorageService_UpdateAuthInfo_Handler,
		},
		{
			MethodName: "DeleteAuthInfo",
			Handler:    _StorageService_DeleteAuthInfo_Handler,
		},
		{
			MethodName: "SetTextInfo",
			Handler:    _StorageService_SetTextInfo_Handler,
		},
		{
			MethodName: "SetBankCardDetails",
			Handler:    _StorageService_SetBankCardDetails_Handler,
		},
		{
			MethodName: "GetTextInfo",
			Handler:    _StorageService_GetTextInfo_Handler,
		},
		{
			MethodName: "GetBankCardDetails",
			Handler:    _StorageService_GetBankCardDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetFileChunkInfo",
			Handler:       _StorageService_SetFileChunkInfo_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetFileChunkInfo",
			Handler:       _StorageService_GetFileChunkInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "keeper.proto",
}
