// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: keeper.proto

package keeperservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AuthInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthInfo) Reset() {
	*x = AuthInfo{}
	mi := &file_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthInfo) ProtoMessage() {}

func (x *AuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthInfo.ProtoReflect.Descriptor instead.
func (*AuthInfo) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *AuthInfo) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *AuthInfo) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthInfo) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type AuthInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AuthInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthInfoList) Reset() {
	*x = AuthInfoList{}
	mi := &file_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthInfoList) ProtoMessage() {}

func (x *AuthInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthInfoList.ProtoReflect.Descriptor instead.
func (*AuthInfoList) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *AuthInfoList) GetList() []*AuthInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type TextInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextInfo) Reset() {
	*x = TextInfo{}
	mi := &file_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInfo) ProtoMessage() {}

func (x *TextInfo) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInfo.ProtoReflect.Descriptor instead.
func (*TextInfo) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *TextInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TextInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextInfo) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type TextInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TextInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextInfoList) Reset() {
	*x = TextInfoList{}
	mi := &file_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInfoList) ProtoMessage() {}

func (x *TextInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInfoList.ProtoReflect.Descriptor instead.
func (*TextInfoList) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{7}
}

func (x *TextInfoList) GetList() []*TextInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type FileChunkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunkInfo) Reset() {
	*x = FileChunkInfo{}
	mi := &file_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunkInfo) ProtoMessage() {}

func (x *FileChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunkInfo.ProtoReflect.Descriptor instead.
func (*FileChunkInfo) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{8}
}

func (x *FileChunkInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileChunkInfo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunkInfo) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type BankCardDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	ExpMonth      uint32                 `protobuf:"varint,2,opt,name=expMonth,proto3" json:"expMonth,omitempty"`
	ExpYear       uint32                 `protobuf:"varint,3,opt,name=expYear,proto3" json:"expYear,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCardDetails) Reset() {
	*x = BankCardDetails{}
	mi := &file_keeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardDetails) ProtoMessage() {}

func (x *BankCardDetails) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardDetails.ProtoReflect.Descriptor instead.
func (*BankCardDetails) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{9}
}

func (x *BankCardDetails) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *BankCardDetails) GetExpMonth() uint32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *BankCardDetails) GetExpYear() uint32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *BankCardDetails) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BankCardDetails) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type BankCardDetailsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*BankCardDetails     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCardDetailsList) Reset() {
	*x = BankCardDetailsList{}
	mi := &file_keeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardDetailsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardDetailsList) ProtoMessage() {}

func (x *BankCardDetailsList) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardDetailsList.ProtoReflect.Descriptor instead.
func (*BankCardDetailsList) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{10}
}

func (x *BankCardDetailsList) GetList() []*BankCardDetails {
	if x != nil {
		return x.List
	}
	return nil
}

type RequestSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSite) Reset() {
	*x = RequestSite{}
	mi := &file_keeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSite) ProtoMessage() {}

func (x *RequestSite) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSite.ProtoReflect.Descriptor instead.
func (*RequestSite) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{11}
}

func (x *RequestSite) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type RequestTitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTitle) Reset() {
	*x = RequestTitle{}
	mi := &file_keeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTitle) ProtoMessage() {}

func (x *RequestTitle) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTitle.ProtoReflect.Descriptor instead.
func (*RequestTitle) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{12}
}

func (x *RequestTitle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RequestFileName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFileName) Reset() {
	*x = RequestFileName{}
	mi := &file_keeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFileName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFileName) ProtoMessage() {}

func (x *RequestFileName) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFileName.ProtoReflect.Descriptor instead.
func (*RequestFileName) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{13}
}

func (x *RequestFileName) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type RequestCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last4         uint32                 `protobuf:"varint,1,opt,name=last4,proto3" json:"last4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCardNumber) Reset() {
	*x = RequestCardNumber{}
	mi := &file_keeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCardNumber) ProtoMessage() {}

func (x *RequestCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCardNumber.ProtoReflect.Descriptor instead.
func (*RequestCardNumber) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{14}
}

func (x *RequestCardNumber) GetLast4() uint32 {
	if x != nil {
		return x.Last4
	}
	return 0
}

var File_keeper_proto protoreflect.FileDescriptor

const file_keeper_proto_rawDesc = "" +
	"\n" +
	"\fkeeper.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"2\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xb6\x01\n" +
	"\bAuthInfo\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12+\n" +
	"\x04meta\x18\x04 \x03(\v2\x17.api.AuthInfo.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\fAuthInfoList\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.api.AuthInfoR\x04list\"\x9a\x01\n" +
	"\bTextInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12+\n" +
	"\x04meta\x18\x03 \x03(\v2\x17.api.TextInfo.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\fTextInfoList\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.api.TextInfoR\x04list\"\xaa\x01\n" +
	"\rFileChunkInfo\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x120\n" +
	"\x04meta\x18\x03 \x03(\v2\x1c.api.FileChunkInfo.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x01\n" +
	"\x0fBankCardDetails\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x1a\n" +
	"\bexpMonth\x18\x02 \x01(\rR\bexpMonth\x12\x18\n" +
	"\aexpYear\x18\x03 \x01(\rR\aexpYear\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x122\n" +
	"\x04meta\x18\x06 \x03(\v2\x1e.api.BankCardDetails.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x13BankCardDetailsList\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.api.BankCardDetailsR\x04list\"!\n" +
	"\vRequestSite\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\"$\n" +
	"\fRequestTitle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"-\n" +
	"\x0fRequestFileName\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\")\n" +
	"\x11RequestCardNumber\x12\x14\n" +
	"\x05last4\x18\x01 \x01(\rR\x05last42w\n" +
	"\vAuthService\x128\n" +
	"\bRegister\x12\x14.api.RegisterRequest\x1a\x16.google.protobuf.Empty\x12.\n" +
	"\x05Login\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse2\xf3\x03\n" +
	"\x0eStorageService\x124\n" +
	"\vSetAuthInfo\x12\r.api.AuthInfo\x1a\x16.google.protobuf.Empty\x124\n" +
	"\vSetTextInfo\x12\r.api.TextInfo\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x10SetFileChunkInfo\x12\x12.api.FileChunkInfo\x1a\x16.google.protobuf.Empty(\x01\x12B\n" +
	"\x12SetBankCardDetails\x12\x14.api.BankCardDetails\x1a\x16.google.protobuf.Empty\x122\n" +
	"\vGetAuthInfo\x12\x10.api.RequestSite\x1a\x11.api.AuthInfoList\x123\n" +
	"\vGetTextInfo\x12\x11.api.RequestTitle\x1a\x11.api.TextInfoList\x12>\n" +
	"\x10GetFileChunkInfo\x12\x14.api.RequestFileName\x1a\x12.api.FileChunkInfo0\x01\x12F\n" +
	"\x12GetBankCardDetails\x12\x16.api.RequestCardNumber\x1a\x18.api.BankCardDetailsListB7Z5github.com/konkovaanna23/gophkeeper/pkg/keeperserviceb\x06proto3"

var (
	file_keeper_proto_rawDescOnce sync.Once
	file_keeper_proto_rawDescData []byte
)

func file_keeper_proto_rawDescGZIP() []byte {
	file_keeper_proto_rawDescOnce.Do(func() {
		file_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keeper_proto_rawDesc), len(file_keeper_proto_rawDesc)))
	})
	return file_keeper_proto_rawDescData
}

var file_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_keeper_proto_goTypes = []any{
	(*RegisterRequest)(nil),     // 0: api.RegisterRequest
	(*RegisterResponse)(nil),    // 1: api.RegisterResponse
	(*LoginRequest)(nil),        // 2: api.LoginRequest
	(*LoginResponse)(nil),       // 3: api.LoginResponse
	(*AuthInfo)(nil),            // 4: api.AuthInfo
	(*AuthInfoList)(nil),        // 5: api.AuthInfoList
	(*TextInfo)(nil),            // 6: api.TextInfo
	(*TextInfoList)(nil),        // 7: api.TextInfoList
	(*FileChunkInfo)(nil),       // 8: api.FileChunkInfo
	(*BankCardDetails)(nil),     // 9: api.BankCardDetails
	(*BankCardDetailsList)(nil), // 10: api.BankCardDetailsList
	(*RequestSite)(nil),         // 11: api.RequestSite
	(*RequestTitle)(nil),        // 12: api.RequestTitle
	(*RequestFileName)(nil),     // 13: api.RequestFileName
	(*RequestCardNumber)(nil),   // 14: api.RequestCardNumber
	nil,                         // 15: api.AuthInfo.MetaEntry
	nil,                         // 16: api.TextInfo.MetaEntry
	nil,                         // 17: api.FileChunkInfo.MetaEntry
	nil,                         // 18: api.BankCardDetails.MetaEntry
	(*emptypb.Empty)(nil),       // 19: google.protobuf.Empty
}
var file_keeper_proto_depIdxs = []int32{
	15, // 0: api.AuthInfo.meta:type_name -> api.AuthInfo.MetaEntry
	4,  // 1: api.AuthInfoList.list:type_name -> api.AuthInfo
	16, // 2: api.TextInfo.meta:type_name -> api.TextInfo.MetaEntry
	6,  // 3: api.TextInfoList.list:type_name -> api.TextInfo
	17, // 4: api.FileChunkInfo.meta:type_name -> api.FileChunkInfo.MetaEntry
	18, // 5: api.BankCardDetails.meta:type_name -> api.BankCardDetails.MetaEntry
	9,  // 6: api.BankCardDetailsList.list:type_name -> api.BankCardDetails
	0,  // 7: api.AuthService.Register:input_type -> api.RegisterRequest
	2,  // 8: api.AuthService.Login:input_type -> api.LoginRequest
	4,  // 9: api.StorageService.SetAuthInfo:input_type -> api.AuthInfo
	6,  // 10: api.StorageService.SetTextInfo:input_type -> api.TextInfo
	8,  // 11: api.StorageService.SetFileChunkInfo:input_type -> api.FileChunkInfo
	9,  // 12: api.StorageService.SetBankCardDetails:input_type -> api.BankCardDetails
	11, // 13: api.StorageService.GetAuthInfo:input_type -> api.RequestSite
	12, // 14: api.StorageService.GetTextInfo:input_type -> api.RequestTitle
	13, // 15: api.StorageService.GetFileChunkInfo:input_type -> api.RequestFileName
	14, // 16: api.StorageService.GetBankCardDetails:input_type -> api.RequestCardNumber
	19, // 17: api.AuthService.Register:output_type -> google.protobuf.Empty
	3,  // 18: api.AuthService.Login:output_type -> api.LoginResponse
	19, // 19: api.StorageService.SetAuthInfo:output_type -> google.protobuf.Empty
	19, // 20: api.StorageService.SetTextInfo:output_type -> google.protobuf.Empty
	19, // 21: api.StorageService.SetFileChunkInfo:output_type -> google.protobuf.Empty
	19, // 22: api.StorageService.SetBankCardDetails:output_type -> google.protobuf.Empty
	5,  // 23: api.StorageService.GetAuthInfo:output_type -> api.AuthInfoList
	7,  // 24: api.StorageService.GetTextInfo:output_type -> api.TextInfoList
	8,  // 25: api.StorageService.GetFileChunkInfo:output_type -> api.FileChunkInfo
	10, // 26: api.StorageService.GetBankCardDetails:output_type -> api.BankCardDetailsList
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_keeper_proto_init() }
func file_keeper_proto_init() {
	if File_keeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keeper_proto_rawDesc), len(file_keeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_keeper_proto_goTypes,
		DependencyIndexes: file_keeper_proto_depIdxs,
		MessageInfos:      file_keeper_proto_msgTypes,
	}.Build()
	File_keeper_proto = out.File
	file_keeper_proto_goTypes = nil
	file_keeper_proto_depIdxs = nil
}
