// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: keeper.proto

package keeperservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AuthInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthInfo) Reset() {
	*x = AuthInfo{}
	mi := &file_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthInfo) ProtoMessage() {}

func (x *AuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthInfo.ProtoReflect.Descriptor instead.
func (*AuthInfo) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *AuthInfo) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthInfo) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type StoredAuthInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *AuthInfo              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredAuthInfo) Reset() {
	*x = StoredAuthInfo{}
	mi := &file_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredAuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredAuthInfo) ProtoMessage() {}

func (x *StoredAuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredAuthInfo.ProtoReflect.Descriptor instead.
func (*StoredAuthInfo) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *StoredAuthInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoredAuthInfo) GetData() *AuthInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StoredAuthInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StoredAuthInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInfoResponse) Reset() {
	*x = CreateInfoResponse{}
	mi := &file_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInfoResponse) ProtoMessage() {}

func (x *CreateInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInfoResponse.ProtoReflect.Descriptor instead.
func (*CreateInfoResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *CreateInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateInfoResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{7}
}

func (x *GetInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateAuthInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *AuthInfo              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuthInfoRequest) Reset() {
	*x = UpdateAuthInfoRequest{}
	mi := &file_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuthInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthInfoRequest) ProtoMessage() {}

func (x *UpdateAuthInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateAuthInfoRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAuthInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAuthInfoRequest) GetData() *AuthInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateAuthInfoRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewVersion    int64                  `protobuf:"varint,1,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInfoResponse) Reset() {
	*x = UpdateInfoResponse{}
	mi := &file_keeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfoResponse) ProtoMessage() {}

func (x *UpdateInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateInfoResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateInfoResponse) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

type DeleteInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInfoRequest) Reset() {
	*x = DeleteInfoRequest{}
	mi := &file_keeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInfoRequest) ProtoMessage() {}

func (x *DeleteInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInfoRequest.ProtoReflect.Descriptor instead.
func (*DeleteInfoRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteInfoRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInfoResponse) Reset() {
	*x = DeleteInfoResponse{}
	mi := &file_keeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInfoResponse) ProtoMessage() {}

func (x *DeleteInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInfoResponse.ProtoReflect.Descriptor instead.
func (*DeleteInfoResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{11}
}

type TextInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextInfo) Reset() {
	*x = TextInfo{}
	mi := &file_keeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInfo) ProtoMessage() {}

func (x *TextInfo) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInfo.ProtoReflect.Descriptor instead.
func (*TextInfo) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{12}
}

func (x *TextInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextInfo) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type StoredTextInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *TextInfo              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredTextInfo) Reset() {
	*x = StoredTextInfo{}
	mi := &file_keeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredTextInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredTextInfo) ProtoMessage() {}

func (x *StoredTextInfo) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredTextInfo.ProtoReflect.Descriptor instead.
func (*StoredTextInfo) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{13}
}

func (x *StoredTextInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoredTextInfo) GetData() *TextInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StoredTextInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StoredTextInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateTextInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *TextInfo              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTextInfoRequest) Reset() {
	*x = UpdateTextInfoRequest{}
	mi := &file_keeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTextInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTextInfoRequest) ProtoMessage() {}

func (x *UpdateTextInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTextInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTextInfoRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateTextInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTextInfoRequest) GetData() *TextInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateTextInfoRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type BankCardDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	ExpMonth      uint32                 `protobuf:"varint,2,opt,name=expMonth,proto3" json:"expMonth,omitempty"`
	ExpYear       uint32                 `protobuf:"varint,3,opt,name=expYear,proto3" json:"expYear,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCardDetails) Reset() {
	*x = BankCardDetails{}
	mi := &file_keeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardDetails) ProtoMessage() {}

func (x *BankCardDetails) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardDetails.ProtoReflect.Descriptor instead.
func (*BankCardDetails) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{15}
}

func (x *BankCardDetails) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *BankCardDetails) GetExpMonth() uint32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *BankCardDetails) GetExpYear() uint32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *BankCardDetails) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BankCardDetails) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type StoredBankCardDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *BankCardDetails       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredBankCardDetails) Reset() {
	*x = StoredBankCardDetails{}
	mi := &file_keeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredBankCardDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredBankCardDetails) ProtoMessage() {}

func (x *StoredBankCardDetails) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredBankCardDetails.ProtoReflect.Descriptor instead.
func (*StoredBankCardDetails) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{16}
}

func (x *StoredBankCardDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoredBankCardDetails) GetData() *BankCardDetails {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StoredBankCardDetails) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StoredBankCardDetails) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateBankCardDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *BankCardDetails       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBankCardDetailsRequest) Reset() {
	*x = UpdateBankCardDetailsRequest{}
	mi := &file_keeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBankCardDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBankCardDetailsRequest) ProtoMessage() {}

func (x *UpdateBankCardDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBankCardDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateBankCardDetailsRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateBankCardDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBankCardDetailsRequest) GetData() *BankCardDetails {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateBankCardDetailsRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StartUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartUploadRequest) Reset() {
	*x = StartUploadRequest{}
	mi := &file_keeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartUploadRequest) ProtoMessage() {}

func (x *StartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartUploadRequest.ProtoReflect.Descriptor instead.
func (*StartUploadRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{18}
}

func (x *StartUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *StartUploadRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StartUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StartUploadRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type StartUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartUploadResponse) Reset() {
	*x = StartUploadResponse{}
	mi := &file_keeper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartUploadResponse) ProtoMessage() {}

func (x *StartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartUploadResponse.ProtoReflect.Descriptor instead.
func (*StartUploadResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{19}
}

func (x *StartUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *StartUploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type UploadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ChunkNo       int64                  `protobuf:"varint,2,opt,name=chunk_no,json=chunkNo,proto3" json:"chunk_no,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkRequest) Reset() {
	*x = UploadChunkRequest{}
	mi := &file_keeper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkRequest) ProtoMessage() {}

func (x *UploadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkRequest.ProtoReflect.Descriptor instead.
func (*UploadChunkRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{20}
}

func (x *UploadChunkRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadChunkRequest) GetChunkNo() int64 {
	if x != nil {
		return x.ChunkNo
	}
	return 0
}

func (x *UploadChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadChunksResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UploadId       string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ReceivedChunks int64                  `protobuf:"varint,2,opt,name=received_chunks,json=receivedChunks,proto3" json:"received_chunks,omitempty"`
	TotalBytes     int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadChunksResponse) Reset() {
	*x = UploadChunksResponse{}
	mi := &file_keeper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunksResponse) ProtoMessage() {}

func (x *UploadChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunksResponse.ProtoReflect.Descriptor instead.
func (*UploadChunksResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{21}
}

func (x *UploadChunksResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadChunksResponse) GetReceivedChunks() int64 {
	if x != nil {
		return x.ReceivedChunks
	}
	return 0
}

func (x *UploadChunksResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type CommitUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitUploadRequest) Reset() {
	*x = CommitUploadRequest{}
	mi := &file_keeper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadRequest) ProtoMessage() {}

func (x *CommitUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadRequest.ProtoReflect.Descriptor instead.
func (*CommitUploadRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{22}
}

func (x *CommitUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CommitUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CommitUploadRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CommitUploadRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type CommitUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	NewVersion    int64                  `protobuf:"varint,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitUploadResponse) Reset() {
	*x = CommitUploadResponse{}
	mi := &file_keeper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadResponse) ProtoMessage() {}

func (x *CommitUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadResponse.ProtoReflect.Descriptor instead.
func (*CommitUploadResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{23}
}

func (x *CommitUploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CommitUploadResponse) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

type FileMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileId         string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	CurrentVersion int64                  `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	Filename       string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Checksum       string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Meta           map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_keeper_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{24}
}

func (x *FileMeta) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileMeta) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *FileMeta) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMeta) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileMeta) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *FileMeta) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetFileMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetaRequest) Reset() {
	*x = GetFileMetaRequest{}
	mi := &file_keeper_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetaRequest) ProtoMessage() {}

func (x *GetFileMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetaRequest.ProtoReflect.Descriptor instead.
func (*GetFileMetaRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{25}
}

func (x *GetFileMetaRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileMeta              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetaResponse) Reset() {
	*x = GetFileMetaResponse{}
	mi := &file_keeper_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetaResponse) ProtoMessage() {}

func (x *GetFileMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetaResponse.ProtoReflect.Descriptor instead.
func (*GetFileMetaResponse) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{26}
}

func (x *GetFileMetaResponse) GetFile() *FileMeta {
	if x != nil {
		return x.File
	}
	return nil
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_keeper_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{27}
}

func (x *DownloadFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadFileRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DownloadFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkNo       int64                  `protobuf:"varint,1,opt,name=chunk_no,json=chunkNo,proto3" json:"chunk_no,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileChunk) Reset() {
	*x = DownloadFileChunk{}
	mi := &file_keeper_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileChunk) ProtoMessage() {}

func (x *DownloadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileChunk.ProtoReflect.Descriptor instead.
func (*DownloadFileChunk) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{28}
}

func (x *DownloadFileChunk) GetChunkNo() int64 {
	if x != nil {
		return x.ChunkNo
	}
	return 0
}

func (x *DownloadFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_keeper_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keeper_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_keeper_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DeleteFileRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_keeper_proto protoreflect.FileDescriptor

const file_keeper_proto_rawDesc = "" +
	"\n" +
	"\fkeeper.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"2\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xa2\x01\n" +
	"\bAuthInfo\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12+\n" +
	"\x04meta\x18\x03 \x03(\v2\x17.api.AuthInfo.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\x0eStoredAuthInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04data\x18\x02 \x01(\v2\r.api.AuthInfoR\x04data\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\">\n" +
	"\x12CreateInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\" \n" +
	"\x0eGetInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"d\n" +
	"\x15UpdateAuthInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04data\x18\x02 \x01(\v2\r.api.AuthInfoR\x04data\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"5\n" +
	"\x12UpdateInfoResponse\x12\x1f\n" +
	"\vnew_version\x18\x01 \x01(\x03R\n" +
	"newVersion\"=\n" +
	"\x11DeleteInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\x14\n" +
	"\x12DeleteInfoResponse\"\x84\x01\n" +
	"\bTextInfo\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12+\n" +
	"\x04meta\x18\x03 \x03(\v2\x17.api.TextInfo.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\x0eStoredTextInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04data\x18\x02 \x01(\v2\r.api.TextInfoR\x04data\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"d\n" +
	"\x15UpdateTextInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04data\x18\x02 \x01(\v2\r.api.TextInfoR\x04data\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\xe2\x01\n" +
	"\x0fBankCardDetails\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x1a\n" +
	"\bexpMonth\x18\x02 \x01(\rR\bexpMonth\x12\x18\n" +
	"\aexpYear\x18\x03 \x01(\rR\aexpYear\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x122\n" +
	"\x04meta\x18\x06 \x03(\v2\x1e.api.BankCardDetails.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\x15StoredBankCardDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.api.BankCardDetailsR\x04data\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"r\n" +
	"\x1cUpdateBankCardDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.api.BankCardDetailsR\x04data\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\xd3\x01\n" +
	"\x12StartUploadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x125\n" +
	"\x04meta\x18\x04 \x03(\v2!.api.StartUploadRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x13StartUploadResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"`\n" +
	"\x12UploadChunkRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x19\n" +
	"\bchunk_no\x18\x02 \x01(\x03R\achunkNo\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"}\n" +
	"\x14UploadChunksResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12'\n" +
	"\x0freceived_chunks\x18\x02 \x01(\x03R\x0ereceivedChunks\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\"\x81\x01\n" +
	"\x13CommitUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"P\n" +
	"\x14CommitUploadResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\x03R\n" +
	"newVersion\"\x89\x02\n" +
	"\bFileMeta\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x03R\x0ecurrentVersion\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12+\n" +
	"\x04meta\x18\x06 \x03(\v2\x17.api.FileMeta.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x12GetFileMetaRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"8\n" +
	"\x13GetFileMetaResponse\x12!\n" +
	"\x04file\x18\x01 \x01(\v2\r.api.FileMetaR\x04file\"H\n" +
	"\x13DownloadFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"B\n" +
	"\x11DownloadFileChunk\x12\x19\n" +
	"\bchunk_no\x18\x01 \x01(\x03R\achunkNo\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"F\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion2v\n" +
	"\vAuthService\x127\n" +
	"\bRegister\x12\x14.api.RegisterRequest\x1a\x15.api.RegisterResponse\x12.\n" +
	"\x05Login\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse2\xca\t\n" +
	"\x0eStorageService\x128\n" +
	"\x0eCreateAuthInfo\x12\r.api.AuthInfo\x1a\x17.api.CreateInfoResponse\x127\n" +
	"\vGetAuthInfo\x12\x13.api.GetInfoRequest\x1a\x13.api.StoredAuthInfo\x12E\n" +
	"\x0eUpdateAuthInfo\x12\x1a.api.UpdateAuthInfoRequest\x1a\x17.api.UpdateInfoResponse\x12A\n" +
	"\x0eDeleteAuthInfo\x12\x16.api.DeleteInfoRequest\x1a\x17.api.DeleteInfoResponse\x128\n" +
	"\x0eCreateTextInfo\x12\r.api.TextInfo\x1a\x17.api.CreateInfoResponse\x127\n" +
	"\vGetTextInfo\x12\x13.api.GetInfoRequest\x1a\x13.api.StoredTextInfo\x12E\n" +
	"\x0eUpdateTextInfo\x12\x1a.api.UpdateTextInfoRequest\x1a\x17.api.UpdateInfoResponse\x12A\n" +
	"\x0eDeleteTextInfo\x12\x16.api.DeleteInfoRequest\x1a\x17.api.DeleteInfoResponse\x12F\n" +
	"\x15CreateBankCardDetails\x12\x14.api.BankCardDetails\x1a\x17.api.CreateInfoResponse\x12E\n" +
	"\x12GetBankCardDetails\x12\x13.api.GetInfoRequest\x1a\x1a.api.StoredBankCardDetails\x12S\n" +
	"\x15UpdateBankCardDetails\x12!.api.UpdateBankCardDetailsRequest\x1a\x17.api.UpdateInfoResponse\x12H\n" +
	"\x15DeleteBankCardDetails\x12\x16.api.DeleteInfoRequest\x1a\x17.api.DeleteInfoResponse\x12@\n" +
	"\vStartUpload\x12\x17.api.StartUploadRequest\x1a\x18.api.StartUploadResponse\x12D\n" +
	"\fUploadChunks\x12\x17.api.UploadChunkRequest\x1a\x19.api.UploadChunksResponse(\x01\x12C\n" +
	"\fCommitUpload\x12\x18.api.CommitUploadRequest\x1a\x19.api.CommitUploadResponse\x12@\n" +
	"\vGetFileMeta\x12\x17.api.GetFileMetaRequest\x1a\x18.api.GetFileMetaResponse\x12B\n" +
	"\fDownloadFile\x12\x18.api.DownloadFileRequest\x1a\x16.api.DownloadFileChunk0\x01\x12=\n" +
	"\n" +
	"DeleteFile\x12\x16.api.DeleteFileRequest\x1a\x17.api.DeleteInfoResponseB7Z5github.com/konkovaanna23/gophkeeper/pkg/keeperserviceb\x06proto3"

var (
	file_keeper_proto_rawDescOnce sync.Once
	file_keeper_proto_rawDescData []byte
)

func file_keeper_proto_rawDescGZIP() []byte {
	file_keeper_proto_rawDescOnce.Do(func() {
		file_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keeper_proto_rawDesc), len(file_keeper_proto_rawDesc)))
	})
	return file_keeper_proto_rawDescData
}

var file_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_keeper_proto_goTypes = []any{
	(*RegisterRequest)(nil),              // 0: api.RegisterRequest
	(*RegisterResponse)(nil),             // 1: api.RegisterResponse
	(*LoginRequest)(nil),                 // 2: api.LoginRequest
	(*LoginResponse)(nil),                // 3: api.LoginResponse
	(*AuthInfo)(nil),                     // 4: api.AuthInfo
	(*StoredAuthInfo)(nil),               // 5: api.StoredAuthInfo
	(*CreateInfoResponse)(nil),           // 6: api.CreateInfoResponse
	(*GetInfoRequest)(nil),               // 7: api.GetInfoRequest
	(*UpdateAuthInfoRequest)(nil),        // 8: api.UpdateAuthInfoRequest
	(*UpdateInfoResponse)(nil),           // 9: api.UpdateInfoResponse
	(*DeleteInfoRequest)(nil),            // 10: api.DeleteInfoRequest
	(*DeleteInfoResponse)(nil),           // 11: api.DeleteInfoResponse
	(*TextInfo)(nil),                     // 12: api.TextInfo
	(*StoredTextInfo)(nil),               // 13: api.StoredTextInfo
	(*UpdateTextInfoRequest)(nil),        // 14: api.UpdateTextInfoRequest
	(*BankCardDetails)(nil),              // 15: api.BankCardDetails
	(*StoredBankCardDetails)(nil),        // 16: api.StoredBankCardDetails
	(*UpdateBankCardDetailsRequest)(nil), // 17: api.UpdateBankCardDetailsRequest
	(*StartUploadRequest)(nil),           // 18: api.StartUploadRequest
	(*StartUploadResponse)(nil),          // 19: api.StartUploadResponse
	(*UploadChunkRequest)(nil),           // 20: api.UploadChunkRequest
	(*UploadChunksResponse)(nil),         // 21: api.UploadChunksResponse
	(*CommitUploadRequest)(nil),          // 22: api.CommitUploadRequest
	(*CommitUploadResponse)(nil),         // 23: api.CommitUploadResponse
	(*FileMeta)(nil),                     // 24: api.FileMeta
	(*GetFileMetaRequest)(nil),           // 25: api.GetFileMetaRequest
	(*GetFileMetaResponse)(nil),          // 26: api.GetFileMetaResponse
	(*DownloadFileRequest)(nil),          // 27: api.DownloadFileRequest
	(*DownloadFileChunk)(nil),            // 28: api.DownloadFileChunk
	(*DeleteFileRequest)(nil),            // 29: api.DeleteFileRequest
	nil,                                  // 30: api.AuthInfo.MetaEntry
	nil,                                  // 31: api.TextInfo.MetaEntry
	nil,                                  // 32: api.BankCardDetails.MetaEntry
	nil,                                  // 33: api.StartUploadRequest.MetaEntry
	nil,                                  // 34: api.FileMeta.MetaEntry
	(*timestamppb.Timestamp)(nil),        // 35: google.protobuf.Timestamp
}
var file_keeper_proto_depIdxs = []int32{
	30, // 0: api.AuthInfo.meta:type_name -> api.AuthInfo.MetaEntry
	4,  // 1: api.StoredAuthInfo.data:type_name -> api.AuthInfo
	35, // 2: api.StoredAuthInfo.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 3: api.UpdateAuthInfoRequest.data:type_name -> api.AuthInfo
	31, // 4: api.TextInfo.meta:type_name -> api.TextInfo.MetaEntry
	12, // 5: api.StoredTextInfo.data:type_name -> api.TextInfo
	35, // 6: api.StoredTextInfo.updated_at:type_name -> google.protobuf.Timestamp
	12, // 7: api.UpdateTextInfoRequest.data:type_name -> api.TextInfo
	32, // 8: api.BankCardDetails.meta:type_name -> api.BankCardDetails.MetaEntry
	15, // 9: api.StoredBankCardDetails.data:type_name -> api.BankCardDetails
	35, // 10: api.StoredBankCardDetails.updated_at:type_name -> google.protobuf.Timestamp
	15, // 11: api.UpdateBankCardDetailsRequest.data:type_name -> api.BankCardDetails
	33, // 12: api.StartUploadRequest.meta:type_name -> api.StartUploadRequest.MetaEntry
	34, // 13: api.FileMeta.meta:type_name -> api.FileMeta.MetaEntry
	24, // 14: api.GetFileMetaResponse.file:type_name -> api.FileMeta
	0,  // 15: api.AuthService.Register:input_type -> api.RegisterRequest
	2,  // 16: api.AuthService.Login:input_type -> api.LoginRequest
	4,  // 17: api.StorageService.CreateAuthInfo:input_type -> api.AuthInfo
	7,  // 18: api.StorageService.GetAuthInfo:input_type -> api.GetInfoRequest
	8,  // 19: api.StorageService.UpdateAuthInfo:input_type -> api.UpdateAuthInfoRequest
	10, // 20: api.StorageService.DeleteAuthInfo:input_type -> api.DeleteInfoRequest
	12, // 21: api.StorageService.CreateTextInfo:input_type -> api.TextInfo
	7,  // 22: api.StorageService.GetTextInfo:input_type -> api.GetInfoRequest
	14, // 23: api.StorageService.UpdateTextInfo:input_type -> api.UpdateTextInfoRequest
	10, // 24: api.StorageService.DeleteTextInfo:input_type -> api.DeleteInfoRequest
	15, // 25: api.StorageService.CreateBankCardDetails:input_type -> api.BankCardDetails
	7,  // 26: api.StorageService.GetBankCardDetails:input_type -> api.GetInfoRequest
	17, // 27: api.StorageService.UpdateBankCardDetails:input_type -> api.UpdateBankCardDetailsRequest
	10, // 28: api.StorageService.DeleteBankCardDetails:input_type -> api.DeleteInfoRequest
	18, // 29: api.StorageService.StartUpload:input_type -> api.StartUploadRequest
	20, // 30: api.StorageService.UploadChunks:input_type -> api.UploadChunkRequest
	22, // 31: api.StorageService.CommitUpload:input_type -> api.CommitUploadRequest
	25, // 32: api.StorageService.GetFileMeta:input_type -> api.GetFileMetaRequest
	27, // 33: api.StorageService.DownloadFile:input_type -> api.DownloadFileRequest
	29, // 34: api.StorageService.DeleteFile:input_type -> api.DeleteFileRequest
	1,  // 35: api.AuthService.Register:output_type -> api.RegisterResponse
	3,  // 36: api.AuthService.Login:output_type -> api.LoginResponse
	6,  // 37: api.StorageService.CreateAuthInfo:output_type -> api.CreateInfoResponse
	5,  // 38: api.StorageService.GetAuthInfo:output_type -> api.StoredAuthInfo
	9,  // 39: api.StorageService.UpdateAuthInfo:output_type -> api.UpdateInfoResponse
	11, // 40: api.StorageService.DeleteAuthInfo:output_type -> api.DeleteInfoResponse
	6,  // 41: api.StorageService.CreateTextInfo:output_type -> api.CreateInfoResponse
	13, // 42: api.StorageService.GetTextInfo:output_type -> api.StoredTextInfo
	9,  // 43: api.StorageService.UpdateTextInfo:output_type -> api.UpdateInfoResponse
	11, // 44: api.StorageService.DeleteTextInfo:output_type -> api.DeleteInfoResponse
	6,  // 45: api.StorageService.CreateBankCardDetails:output_type -> api.CreateInfoResponse
	16, // 46: api.StorageService.GetBankCardDetails:output_type -> api.StoredBankCardDetails
	9,  // 47: api.StorageService.UpdateBankCardDetails:output_type -> api.UpdateInfoResponse
	11, // 48: api.StorageService.DeleteBankCardDetails:output_type -> api.DeleteInfoResponse
	19, // 49: api.StorageService.StartUpload:output_type -> api.StartUploadResponse
	21, // 50: api.StorageService.UploadChunks:output_type -> api.UploadChunksResponse
	23, // 51: api.StorageService.CommitUpload:output_type -> api.CommitUploadResponse
	26, // 52: api.StorageService.GetFileMeta:output_type -> api.GetFileMetaResponse
	28, // 53: api.StorageService.DownloadFile:output_type -> api.DownloadFileChunk
	11, // 54: api.StorageService.DeleteFile:output_type -> api.DeleteInfoResponse
	35, // [35:55] is the sub-list for method output_type
	15, // [15:35] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_keeper_proto_init() }
func file_keeper_proto_init() {
	if File_keeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keeper_proto_rawDesc), len(file_keeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_keeper_proto_goTypes,
		DependencyIndexes: file_keeper_proto_depIdxs,
		MessageInfos:      file_keeper_proto_msgTypes,
	}.Build()
	File_keeper_proto = out.File
	file_keeper_proto_goTypes = nil
	file_keeper_proto_depIdxs = nil
}
