// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: keeper.proto

package keeperservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Register_FullMethodName = "/api.AuthService/Register"
	AuthService_Login_FullMethodName    = "/api.AuthService/Login"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AuthService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keeper.proto",
}

const (
	StorageService_CreateAuthInfo_FullMethodName        = "/api.StorageService/CreateAuthInfo"
	StorageService_GetAuthInfo_FullMethodName           = "/api.StorageService/GetAuthInfo"
	StorageService_UpdateAuthInfo_FullMethodName        = "/api.StorageService/UpdateAuthInfo"
	StorageService_DeleteAuthInfo_FullMethodName        = "/api.StorageService/DeleteAuthInfo"
	StorageService_CreateTextInfo_FullMethodName        = "/api.StorageService/CreateTextInfo"
	StorageService_GetTextInfo_FullMethodName           = "/api.StorageService/GetTextInfo"
	StorageService_UpdateTextInfo_FullMethodName        = "/api.StorageService/UpdateTextInfo"
	StorageService_DeleteTextInfo_FullMethodName        = "/api.StorageService/DeleteTextInfo"
	StorageService_CreateBankCardDetails_FullMethodName = "/api.StorageService/CreateBankCardDetails"
	StorageService_GetBankCardDetails_FullMethodName    = "/api.StorageService/GetBankCardDetails"
	StorageService_UpdateBankCardDetails_FullMethodName = "/api.StorageService/UpdateBankCardDetails"
	StorageService_DeleteBankCardDetails_FullMethodName = "/api.StorageService/DeleteBankCardDetails"
	StorageService_StartUpload_FullMethodName           = "/api.StorageService/StartUpload"
	StorageService_UploadChunks_FullMethodName          = "/api.StorageService/UploadChunks"
	StorageService_CommitUpload_FullMethodName          = "/api.StorageService/CommitUpload"
	StorageService_GetFileMeta_FullMethodName           = "/api.StorageService/GetFileMeta"
	StorageService_DownloadFile_FullMethodName          = "/api.StorageService/DownloadFile"
	StorageService_DeleteFile_FullMethodName            = "/api.StorageService/DeleteFile"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServiceClient interface {
	CreateAuthInfo(ctx context.Context, in *AuthInfo, opts ...grpc.CallOption) (*CreateInfoResponse, error)
	GetAuthInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*StoredAuthInfo, error)
	UpdateAuthInfo(ctx context.Context, in *UpdateAuthInfoRequest, opts ...grpc.CallOption) (*UpdateInfoResponse, error)
	DeleteAuthInfo(ctx context.Context, in *DeleteInfoRequest, opts ...grpc.CallOption) (*DeleteInfoResponse, error)
	CreateTextInfo(ctx context.Context, in *TextInfo, opts ...grpc.CallOption) (*CreateInfoResponse, error)
	GetTextInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*StoredTextInfo, error)
	UpdateTextInfo(ctx context.Context, in *UpdateTextInfoRequest, opts ...grpc.CallOption) (*UpdateInfoResponse, error)
	DeleteTextInfo(ctx context.Context, in *DeleteInfoRequest, opts ...grpc.CallOption) (*DeleteInfoResponse, error)
	CreateBankCardDetails(ctx context.Context, in *BankCardDetails, opts ...grpc.CallOption) (*CreateInfoResponse, error)
	GetBankCardDetails(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*StoredBankCardDetails, error)
	UpdateBankCardDetails(ctx context.Context, in *UpdateBankCardDetailsRequest, opts ...grpc.CallOption) (*UpdateInfoResponse, error)
	DeleteBankCardDetails(ctx context.Context, in *DeleteInfoRequest, opts ...grpc.CallOption) (*DeleteInfoResponse, error)
	StartUpload(ctx context.Context, in *StartUploadRequest, opts ...grpc.CallOption) (*StartUploadResponse, error)
	UploadChunks(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunkRequest, UploadChunksResponse], error)
	CommitUpload(ctx context.Context, in *CommitUploadRequest, opts ...grpc.CallOption) (*CommitUploadResponse, error)
	GetFileMeta(ctx context.Context, in *GetFileMetaRequest, opts ...grpc.CallOption) (*GetFileMetaResponse, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadFileChunk], error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteInfoResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) CreateAuthInfo(ctx context.Context, in *AuthInfo, opts ...grpc.CallOption) (*CreateInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_CreateAuthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetAuthInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*StoredAuthInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoredAuthInfo)
	err := c.cc.Invoke(ctx, StorageService_GetAuthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UpdateAuthInfo(ctx context.Context, in *UpdateAuthInfoRequest, opts ...grpc.CallOption) (*UpdateInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_UpdateAuthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteAuthInfo(ctx context.Context, in *DeleteInfoRequest, opts ...grpc.CallOption) (*DeleteInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteAuthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CreateTextInfo(ctx context.Context, in *TextInfo, opts ...grpc.CallOption) (*CreateInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_CreateTextInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetTextInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*StoredTextInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoredTextInfo)
	err := c.cc.Invoke(ctx, StorageService_GetTextInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UpdateTextInfo(ctx context.Context, in *UpdateTextInfoRequest, opts ...grpc.CallOption) (*UpdateInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_UpdateTextInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteTextInfo(ctx context.Context, in *DeleteInfoRequest, opts ...grpc.CallOption) (*DeleteInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteTextInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CreateBankCardDetails(ctx context.Context, in *BankCardDetails, opts ...grpc.CallOption) (*CreateInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_CreateBankCardDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetBankCardDetails(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*StoredBankCardDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoredBankCardDetails)
	err := c.cc.Invoke(ctx, StorageService_GetBankCardDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UpdateBankCardDetails(ctx context.Context, in *UpdateBankCardDetailsRequest, opts ...grpc.CallOption) (*UpdateInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_UpdateBankCardDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteBankCardDetails(ctx context.Context, in *DeleteInfoRequest, opts ...grpc.CallOption) (*DeleteInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteBankCardDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) StartUpload(ctx context.Context, in *StartUploadRequest, opts ...grpc.CallOption) (*StartUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartUploadResponse)
	err := c.cc.Invoke(ctx, StorageService_StartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UploadChunks(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunkRequest, UploadChunksResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_UploadChunks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunkRequest, UploadChunksResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_UploadChunksClient = grpc.ClientStreamingClient[UploadChunkRequest, UploadChunksResponse]

func (c *storageServiceClient) CommitUpload(ctx context.Context, in *CommitUploadRequest, opts ...grpc.CallOption) (*CommitUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitUploadResponse)
	err := c.cc.Invoke(ctx, StorageService_CommitUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetFileMeta(ctx context.Context, in *GetFileMetaRequest, opts ...grpc.CallOption) (*GetFileMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileMetaResponse)
	err := c.cc.Invoke(ctx, StorageService_GetFileMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[1], StorageService_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFileRequest, DownloadFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_DownloadFileClient = grpc.ServerStreamingClient[DownloadFileChunk]

func (c *storageServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInfoResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
type StorageServiceServer interface {
	CreateAuthInfo(context.Context, *AuthInfo) (*CreateInfoResponse, error)
	GetAuthInfo(context.Context, *GetInfoRequest) (*StoredAuthInfo, error)
	UpdateAuthInfo(context.Context, *UpdateAuthInfoRequest) (*UpdateInfoResponse, error)
	DeleteAuthInfo(context.Context, *DeleteInfoRequest) (*DeleteInfoResponse, error)
	CreateTextInfo(context.Context, *TextInfo) (*CreateInfoResponse, error)
	GetTextInfo(context.Context, *GetInfoRequest) (*StoredTextInfo, error)
	UpdateTextInfo(context.Context, *UpdateTextInfoRequest) (*UpdateInfoResponse, error)
	DeleteTextInfo(context.Context, *DeleteInfoRequest) (*DeleteInfoResponse, error)
	CreateBankCardDetails(context.Context, *BankCardDetails) (*CreateInfoResponse, error)
	GetBankCardDetails(context.Context, *GetInfoRequest) (*StoredBankCardDetails, error)
	UpdateBankCardDetails(context.Context, *UpdateBankCardDetailsRequest) (*UpdateInfoResponse, error)
	DeleteBankCardDetails(context.Context, *DeleteInfoRequest) (*DeleteInfoResponse, error)
	StartUpload(context.Context, *StartUploadRequest) (*StartUploadResponse, error)
	UploadChunks(grpc.ClientStreamingServer[UploadChunkRequest, UploadChunksResponse]) error
	CommitUpload(context.Context, *CommitUploadRequest) (*CommitUploadResponse, error)
	GetFileMeta(context.Context, *GetFileMetaRequest) (*GetFileMetaResponse, error)
	DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[DownloadFileChunk]) error
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteInfoResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) CreateAuthInfo(context.Context, *AuthInfo) (*CreateInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuthInfo not implemented")
}
func (UnimplementedStorageServiceServer) GetAuthInfo(context.Context, *GetInfoRequest) (*StoredAuthInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthInfo not implemented")
}
func (UnimplementedStorageServiceServer) UpdateAuthInfo(context.Context, *UpdateAuthInfoRequest) (*UpdateInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAuthInfo not implemented")
}
func (UnimplementedStorageServiceServer) DeleteAuthInfo(context.Context, *DeleteInfoRequest) (*DeleteInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAuthInfo not implemented")
}
func (UnimplementedStorageServiceServer) CreateTextInfo(context.Context, *TextInfo) (*CreateInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTextInfo not implemented")
}
func (UnimplementedStorageServiceServer) GetTextInfo(context.Context, *GetInfoRequest) (*StoredTextInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTextInfo not implemented")
}
func (UnimplementedStorageServiceServer) UpdateTextInfo(context.Context, *UpdateTextInfoRequest) (*UpdateInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTextInfo not implemented")
}
func (UnimplementedStorageServiceServer) DeleteTextInfo(context.Context, *DeleteInfoRequest) (*DeleteInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTextInfo not implemented")
}
func (UnimplementedStorageServiceServer) CreateBankCardDetails(context.Context, *BankCardDetails) (*CreateInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBankCardDetails not implemented")
}
func (UnimplementedStorageServiceServer) GetBankCardDetails(context.Context, *GetInfoRequest) (*StoredBankCardDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBankCardDetails not implemented")
}
func (UnimplementedStorageServiceServer) UpdateBankCardDetails(context.Context, *UpdateBankCardDetailsRequest) (*UpdateInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBankCardDetails not implemented")
}
func (UnimplementedStorageServiceServer) DeleteBankCardDetails(context.Context, *DeleteInfoRequest) (*DeleteInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBankCardDetails not implemented")
}
func (UnimplementedStorageServiceServer) StartUpload(context.Context, *StartUploadRequest) (*StartUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartUpload not implemented")
}
func (UnimplementedStorageServiceServer) UploadChunks(grpc.ClientStreamingServer[UploadChunkRequest, UploadChunksResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadChunks not implemented")
}
func (UnimplementedStorageServiceServer) CommitUpload(context.Context, *CommitUploadRequest) (*CommitUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitUpload not implemented")
}
func (UnimplementedStorageServiceServer) GetFileMeta(context.Context, *GetFileMetaRequest) (*GetFileMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileMeta not implemented")
}
func (UnimplementedStorageServiceServer) DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[DownloadFileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedStorageServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_CreateAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreateAuthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateAuthInfo(ctx, req.(*AuthInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetAuthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetAuthInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UpdateAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAuthInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).UpdateAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_UpdateAuthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).UpdateAuthInfo(ctx, req.(*UpdateAuthInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteAuthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteAuthInfo(ctx, req.(*DeleteInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CreateTextInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateTextInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreateTextInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateTextInfo(ctx, req.(*TextInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetTextInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetTextInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetTextInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetTextInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UpdateTextInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTextInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).UpdateTextInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_UpdateTextInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).UpdateTextInfo(ctx, req.(*UpdateTextInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteTextInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteTextInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteTextInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteTextInfo(ctx, req.(*DeleteInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CreateBankCardDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankCardDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateBankCardDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreateBankCardDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateBankCardDetails(ctx, req.(*BankCardDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetBankCardDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetBankCardDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetBankCardDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetBankCardDetails(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UpdateBankCardDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBankCardDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).UpdateBankCardDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_UpdateBankCardDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).UpdateBankCardDetails(ctx, req.(*UpdateBankCardDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteBankCardDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteBankCardDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteBankCardDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteBankCardDetails(ctx, req.(*DeleteInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_StartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).StartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_StartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).StartUpload(ctx, req.(*StartUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UploadChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).UploadChunks(&grpc.GenericServerStream[UploadChunkRequest, UploadChunksResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_UploadChunksServer = grpc.ClientStreamingServer[UploadChunkRequest, UploadChunksResponse]

func _StorageService_CommitUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CommitUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CommitUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CommitUpload(ctx, req.(*CommitUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetFileMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetFileMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetFileMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetFileMeta(ctx, req.(*GetFileMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).DownloadFile(m, &grpc.GenericServerStream[DownloadFileRequest, DownloadFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_DownloadFileServer = grpc.ServerStreamingServer[DownloadFileChunk]

func _StorageService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuthInfo",
			Handler:    _StorageService_CreateAuthInfo_Handler,
		},
		{
			MethodName: "GetAuthInfo",
			Handler:    _StorageService_GetAuthInfo_Handler,
		},
		{
			MethodName: "UpdateAuthInfo",
			Handler:    _StorageService_UpdateAuthInfo_Handler,
		},
		{
			MethodName: "DeleteAuthInfo",
			Handler:    _StorageService_DeleteAuthInfo_Handler,
		},
		{
			MethodName: "CreateTextInfo",
			Handler:    _StorageService_CreateTextInfo_Handler,
		},
		{
			MethodName: "GetTextInfo",
			Handler:    _StorageService_GetTextInfo_Handler,
		},
		{
			MethodName: "UpdateTextInfo",
			Handler:    _StorageService_UpdateTextInfo_Handler,
		},
		{
			MethodName: "DeleteTextInfo",
			Handler:    _StorageService_DeleteTextInfo_Handler,
		},
		{
			MethodName: "CreateBankCardDetails",
			Handler:    _StorageService_CreateBankCardDetails_Handler,
		},
		{
			MethodName: "GetBankCardDetails",
			Handler:    _StorageService_GetBankCardDetails_Handler,
		},
		{
			MethodName: "UpdateBankCardDetails",
			Handler:    _StorageService_UpdateBankCardDetails_Handler,
		},
		{
			MethodName: "DeleteBankCardDetails",
			Handler:    _StorageService_DeleteBankCardDetails_Handler,
		},
		{
			MethodName: "StartUpload",
			Handler:    _StorageService_StartUpload_Handler,
		},
		{
			MethodName: "CommitUpload",
			Handler:    _StorageService_CommitUpload_Handler,
		},
		{
			MethodName: "GetFileMeta",
			Handler:    _StorageService_GetFileMeta_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _StorageService_DeleteFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadChunks",
			Handler:       _StorageService_UploadChunks_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _StorageService_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "keeper.proto",
}
